# Generated by Django 6.0.2 on 2026-02-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=100)),
                ('asientos', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
